export interface BreedArticle {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  breedName: string;
  size: 'Small' | 'Medium' | 'Large' | 'Giant';
  weight: string;
  lifespan: string;
  avgLifespan: string;
  humanAgeAt5: number | string;
  humanAgeAt10: number | string;
  lifeStages: string;
  overview: string;
  lifespanFactors: string[];
  commonHealthIssues: { issue: string; description: string }[];
  lifeStageCare: { stage: string; description: string }[];
  tips: string[];
  relatedSearches: string[];
}

const breedArticles: Record<string, BreedArticle> = {
  'labrador-retriever-lifespan': {
    slug: 'labrador-retriever-lifespan',
    title: 'Labrador Retriever Lifespan: How Long Do Labs Live?',
    metaTitle: 'Labrador Retriever Lifespan: How Long Do Labs Live? | Complete Guide',
    metaDescription: 'Learn about Labrador Retriever lifespan (10-12 years), common health issues like hip dysplasia and obesity, and proven tips to help your Lab live longer. Complete Labrador care guide.',
    breedName: 'Labrador Retriever',
    size: 'Large',
    weight: '55-80 lbs',
    lifespan: '10-12 years',
    avgLifespan: '11 years',
    humanAgeAt5: 39,
    humanAgeAt10: 64,
    lifeStages: 'Puppy: 0-1yr | Young Adult: 1-2yr | Adult: 2-7yr | Senior: 7-10yr | Geriatric: 10yr+',
    overview: 'The Labrador Retriever is one of the most popular dog breeds in the world, cherished for their friendly temperament, intelligence, and versatility. Originally bred as working dogs in Newfoundland, Labs have become beloved family companions, service dogs, and hunting partners. Understanding the Labrador Retriever lifespan is essential for providing the best care throughout every stage of your Lab\'s life.',
    lifespanFactors: [
      'Genetics and lineage quality from responsible breeders',
      'Diet quality and portion control to prevent obesity',
      'Regular exercise and physical activity levels',
      'Preventive veterinary care and health screenings',
      'Dental hygiene and oral health maintenance',
      'Environmental factors and living conditions',
    ],
    commonHealthIssues: [
      { issue: 'Hip Dysplasia', description: 'A genetic condition where the hip joint doesn\'t fit properly, leading to arthritis and pain. Affects approximately 12% of Labrador Retrievers. Weight management and joint supplements can help manage symptoms.' },
      { issue: 'Elbow Dysplasia', description: 'Similar to hip dysplasia but affecting the elbow joints. Common in large breeds and can cause lameness. Surgical options are available for severe cases.' },
      { issue: 'Obesity', description: 'Labradors are prone to obesity due to a genetic variant affecting appetite regulation. Over 60% of Labs are overweight or obese, which reduces lifespan by 1-2 years.' },
      { issue: 'Progressive Retinal Atrophy (PRA)', description: 'An inherited eye disease that causes gradual vision loss leading to blindness. Genetic testing can identify carriers.' },
      { issue: 'Exercise-Induced Collapse (EIC)', description: 'A genetic condition causing weakness and collapse after intense exercise. Affects 3-5% of Labs. DNA testing is available.' },
      { issue: 'Ear Infections', description: 'Lab\'s floppy ears trap moisture, making them susceptible to bacterial and yeast infections. Regular ear cleaning is essential.' },
    ],
    lifeStageCare: [
      { stage: 'Puppy (0-1 year)', description: 'Feed high-quality large-breed puppy food to support controlled growth. Begin socialization and basic obedience training early. Schedule vaccinations and deworming as recommended by your vet. Avoid excessive high-impact exercise on developing joints.' },
      { stage: 'Young Adult (1-2 years)', description: 'Transition to adult dog food with appropriate protein and fat levels. Establish a consistent exercise routine of 60-90 minutes daily. Continue training reinforcement and mental stimulation activities. Schedule annual veterinary checkups.' },
      { stage: 'Adult (2-7 years)', description: 'Maintain ideal body weight through portion control and regular exercise. Keep mentally stimulated with puzzle toys and new activities. Continue annual vet visits with blood work baselines. Monitor for early signs of joint issues.' },
      { stage: 'Senior (7-10 years)', description: 'Switch to senior dog food with joint support supplements. Reduce exercise intensity but maintain daily walks. Schedule bi-annual veterinary checkups with comprehensive blood work. Watch for signs of arthritis, vision changes, and cognitive decline.' },
      { stage: 'Geriatric (10+ years)', description: 'Provide orthopedic bedding and easy access to food and water. Consider ramps for stairs and vehicles. Monitor closely for pain signals and adjust pain management with vet guidance. Focus on quality of life and comfort.' },
    ],
    tips: [
      'Keep your Lab at a lean body weight — you should be able to feel their ribs without excess fat covering',
      'Provide at least 60 minutes of daily exercise, split into two or more sessions',
      'Use puzzle feeders to slow down eating and provide mental stimulation',
      'Brush teeth 2-3 times per week to prevent periodontal disease',
      'Schedule annual hip and elbow evaluations, especially for active working dogs',
      'Consider pet insurance early, before pre-existing conditions develop',
      'Socialize your Lab with other dogs and people throughout their life',
    ],
    relatedSearches: [
      'labrador retriever lifespan',
      'how long do labs live',
      'labrador health problems',
      'labrador retriever life expectancy',
      'oldest labrador retriever',
      'labrador retriever hip dysplasia',
    ],
  },

  'german-shepherd-lifespan': {
    slug: 'german-shepherd-lifespan',
    title: 'German Shepherd Lifespan and Health Guide',
    metaTitle: 'German Shepherd Lifespan: How Long Do German Shepherds Live? | Health Guide',
    metaDescription: 'Comprehensive German Shepherd lifespan guide (9-12 years). Learn about common health issues, degenerative myelopathy, hip dysplasia, and how to maximize your GSD\'s healthy years.',
    breedName: 'German Shepherd',
    size: 'Large',
    weight: '50-90 lbs',
    lifespan: '9-12 years',
    avgLifespan: '10.5 years',
    humanAgeAt5: 39,
    humanAgeAt10: 64,
    lifeStages: 'Puppy: 0-1yr | Young Adult: 1-2yr | Adult: 2-6yr | Senior: 6-9yr | Geriatric: 9yr+',
    overview: 'The German Shepherd Dog (GSD) is renowned for its intelligence, loyalty, and versatility. Originally developed in Germany for herding sheep, German Shepherds now serve in police work, military roles, search and rescue, and as devoted family companions. Their working heritage contributes to specific health considerations that owners should understand to maximize their German Shepherd\'s lifespan.',
    lifespanFactors: [
      'Breeding practices and genetic screening of parents',
      'Weight management — obesity significantly impacts joint health',
      'Exercise intensity appropriate for age and health status',
      'Early screening for degenerative myelopathy (DM)',
      'Hip and elbow dysplasia prevention and management',
      'Quality nutrition with joint-supporting supplements',
    ],
    commonHealthIssues: [
      { issue: 'Hip Dysplasia', description: 'Affects approximately 19% of German Shepherds. This genetic condition causes malformation of the hip joint, leading to arthritis and mobility issues. Responsible breeders screen for this condition.' },
      { issue: 'Degenerative Myelopathy (DM)', description: 'A progressive spinal cord disease similar to ALS in humans. Affects approximately 2% of GSDs, typically appearing in dogs 8+ years old. DNA testing can identify at-risk dogs.' },
      { issue: 'Bloat (Gastric Dilatation-Volvulus)', description: 'A life-threatening emergency where the stomach twists on itself. Large, deep-chested breeds like GSDs are at high risk. Feed multiple small meals and avoid exercise immediately after eating.' },
      { issue: 'Elbow Dysplasia', description: 'An inherited condition affecting the elbow joint that can cause lameness. Weight control and joint supplements help manage symptoms.' },
      { issue: 'Exocrine Pancreatic Insufficiency (EPI)', description: 'A condition where the pancreas fails to produce enough digestive enzymes, leading to weight loss and malnutrition despite a good appetite. Affects about 1% of GSDs.' },
    ],
    lifeStageCare: [
      { stage: 'Puppy (0-1 year)', description: 'Feed large-breed puppy food for controlled growth. Begin early socialization — German Shepherds need extensive positive exposure to people, places, and situations. Start basic obedience training early to channel intelligence constructively.' },
      { stage: 'Young Adult (1-2 years)', description: 'Transition to adult food. Establish a consistent exercise routine including both physical activity and mental challenges. German Shepherds need a "job" — training, agility, scent work, or structured play. Continue socialization throughout this period.' },
      { stage: 'Adult (2-6 years)', description: 'Maintain rigorous exercise: 60-90 minutes daily of combined physical and mental activity. Schedule annual vet visits with hip evaluations. Monitor weight carefully — excess weight accelerates joint degeneration. Consider pet insurance before age-related issues develop.' },
      { stage: 'Senior (6-9 years)', description: 'Watch for early signs of DM: hind leg weakness, knuckling, or dragging paws. Reduce high-impact exercise but maintain daily walks. Switch to senior food with glucosamine and chondroitin. Increase vet visits to bi-annual.' },
      { stage: 'Geriatric (9+ years)', description: 'Provide non-slip flooring surfaces. Consider mobility aids like harnesses and ramps. Monitor for signs of pain or cognitive decline. Adjust home environment for accessibility. Focus on comfort and quality of life.' },
    ],
    tips: [
      'Choose a reputable breeder who performs OFA hip/elbow certifications and DM DNA testing',
      'Feed 2-3 smaller meals daily instead of one large meal to reduce bloat risk',
      'Provide mental stimulation through puzzle toys, training sessions, and scent games',
      'Start joint supplements (glucosamine, chondroitin, MSM) early as a preventive measure',
      'Maintain a lean body condition — you should see a visible waist from above',
      'Brush teeth regularly — German Shepherds are prone to periodontal disease',
      'Consider gastropexy surgery (stomach tacking) during spay/neuter to prevent bloat',
    ],
    relatedSearches: [
      'german shepherd lifespan',
      'how long do german shepherds live',
      'german shepherd health problems',
      'german shepherd degenerative myelopathy',
      'german shepherd life expectancy',
      'german shepherd hip dysplasia',
    ],
  },

  'golden-retriever-lifespan': {
    slug: 'golden-retriever-lifespan',
    title: 'Golden Retriever Lifespan: Complete Care Guide',
    metaTitle: 'Golden Retriever Lifespan: How Long Do Golden Retrievers Live? | Care Guide',
    metaDescription: 'Complete Golden Retriever lifespan guide (10-13 years). Learn about cancer risks, hip dysplasia, heart conditions, and expert tips to help your Golden Retriever live a longer, healthier life.',
    breedName: 'Golden Retriever',
    size: 'Large',
    weight: '55-75 lbs',
    lifespan: '10-13 years',
    avgLifespan: '11.5 years',
    humanAgeAt5: 39,
    humanAgeAt10: 64,
    lifeStages: 'Puppy: 0-1yr | Young Adult: 1-2yr | Adult: 2-7yr | Senior: 7-10yr | Geriatric: 10yr+',
    overview: 'Golden Retrievers are beloved worldwide for their friendly, tolerant attitude and beautiful golden coats. As one of America\'s most popular breeds, they excel as family pets, therapy dogs, and service animals. However, Golden Retrievers face specific health challenges — particularly high cancer rates — that owners should understand to maximize their dog\'s healthy years.',
    lifespanFactors: [
      'Cancer risk — Goldens have one of the highest cancer rates among all breeds',
      'Genetic lineage and health certifications from breeders',
      'Diet quality, particularly antioxidant-rich foods',
      'Regular exercise to maintain healthy weight and joint function',
      'Early cancer screening and preventive veterinary care',
      'Environmental toxin exposure (pesticides, lawn chemicals)',
    ],
    commonHealthIssues: [
      { issue: 'Cancer', description: 'The leading cause of death in Golden Retrievers, affecting approximately 60% of Goldens. Hemangiosarcoma, lymphoma, and osteosarcoma are most common. Studies suggest neutering may increase certain cancer risks.' },
      { issue: 'Hip Dysplasia', description: 'Affects about 20% of Golden Retrievers. This genetic condition causes improper hip joint development. Weight management, exercise, and joint supplements are key management strategies.' },
      { issue: 'Elbow Dysplasia', description: 'Common in large breeds, affecting the elbow joint. Can cause lameness and arthritis. Surgical intervention may be needed for severe cases.' },
      { issue: 'Heart Conditions', description: 'Subvalvular aortic stenosis (SAS) is a congenital heart defect that can affect Goldens. Regular cardiac evaluations are recommended for breeding dogs.' },
      { issue: 'Hypothyroidism', description: 'An underactive thyroid gland that causes weight gain, hair loss, and lethargy. Easily managed with daily medication once diagnosed.' },
      { issue: 'Ear Infections', description: 'Golden Retrievers\' floppy ears create a warm, moist environment ideal for infections. Regular ear cleaning and drying after swimming are essential.' },
    ],
    lifeStageCare: [
      { stage: 'Puppy (0-1 year)', description: 'Feed high-quality large-breed puppy food. Begin early socialization and positive reinforcement training. Avoid over-exercising on hard surfaces while joints are developing. Schedule all puppy vaccinations.' },
      { stage: 'Young Adult (1-2 years)', description: 'Transition to adult formula food. Establish a daily exercise routine of 60+ minutes. Goldens love swimming, fetch, and hiking. Continue obedience training and consider therapy dog certification.' },
      { stage: 'Adult (2-7 years)', description: 'Maintain ideal body weight — Goldens love food and can easily become overweight. Provide daily exercise and mental stimulation. Schedule annual vet visits with blood work. Monitor for lumps and bumps.' },
      { stage: 'Senior (7-10 years)', description: 'Switch to senior formula with joint support. Reduce high-impact exercise. Schedule bi-annual vet checks with comprehensive screenings including cancer checks. Watch for signs of arthritis and cognitive decline.' },
      { stage: 'Geriatric (10+ years)', description: 'Provide orthopedic bedding and easy home access. Monitor for cancer warning signs: unexplained weight loss, lethargy, lumps, or bleeding. Focus on comfort, pain management, and quality time together.' },
    ],
    tips: [
      'Feed antioxidant-rich foods (blueberries, carrots) to potentially reduce cancer risk',
      'Brush your Golden\'s coat 2-3 times per week to prevent matting and spot skin issues early',
      'Clean ears weekly, especially after swimming or bathing',
      'Schedule bi-annual vet visits for Goldens over 7 years old',
      'Consider pet insurance early in your Golden\'s life for cancer-related coverage',
      'Provide daily joint supplements starting in adulthood',
      'Monitor your Golden\'s weight closely — even a few extra pounds strain joints',
    ],
    relatedSearches: [
      'golden retriever lifespan',
      'how long do golden retrievers live',
      'golden retriever cancer',
      'golden retriever health problems',
      'golden retriever life expectancy',
      'why do golden retrievers get cancer',
    ],
  },

  'french-bulldog-lifespan': {
    slug: 'french-bulldog-lifespan',
    title: 'French Bulldog Lifespan: What French Bulldog Owners Should Know',
    metaTitle: 'French Bulldog Lifespan: How Long Do French Bulldogs Live? | Complete Guide',
    metaDescription: 'Complete French Bulldog lifespan guide (10-12 years). Learn about brachycephalic health issues, IVDD, allergies, and essential care tips for your Frenchie at every life stage.',
    breedName: 'French Bulldog',
    size: 'Small',
    weight: '16-28 lbs',
    lifespan: '10-12 years',
    avgLifespan: '11 years',
    humanAgeAt5: 36,
    humanAgeAt10: 56,
    lifeStages: 'Puppy: 0-1yr | Young Adult: 1-2yr | Adult: 2-8yr | Senior: 8-10yr | Geriatric: 10yr+',
    overview: 'French Bulldogs, affectionately known as "Frenchies," have skyrocketed in popularity to become one of America\'s most beloved breeds. With their bat-like ears, compact bodies, and charming personalities, Frenchies make excellent apartment companions. However, their unique physical characteristics come with significant health considerations that directly impact their lifespan and quality of life.',
    lifespanFactors: [
      'Brachycephalic airway syndrome severity',
      'Spine health and intervertebral disc disease (IVDD) prevention',
      'Temperature regulation — French Bulldogs overheat easily',
      'Skin fold hygiene and allergy management',
      'Responsible breeding practices with health testing',
      'Weight management — even small weight gains stress their small frames',
    ],
    commonHealthIssues: [
      { issue: 'Brachycephalic Airway Syndrome', description: 'Due to their flat faces, Frenchies often have narrowed nostrils, elongated soft palates, and narrowed airways. This causes breathing difficulties, snoring, and heat intolerance. Severe cases may require surgery.' },
      { issue: 'Intervertebral Disc Disease (IVDD)', description: 'French Bulldogs are prone to spinal disc problems due to their chondrodystrophic (short-legged) body type. IVDD can cause pain, paralysis, and requires emergency veterinary care.' },
      { issue: 'Skin Allergies and Infections', description: 'French Bulldogs commonly suffer from environmental and food allergies that cause itchy skin, ear infections, and skin fold dermatitis. Regular skin fold cleaning is essential.' },
      { issue: 'Hip Dysplasia', description: 'Despite their small size, French Bulldogs have a high rate of hip dysplasia. OFA testing shows about 20% of Frenchies have abnormal hips.' },
      { issue: 'Eye Problems', description: 'Their prominent eyes are vulnerable to injuries, cherry eye (prolapsed gland), dry eye, and corneal ulcers. Regular eye examinations are important.' },
      { issue: 'Patellar Luxation', description: 'A condition where the kneecap slips out of place, causing intermittent lameness. Common in small breeds and can range from mild to severe.' },
    ],
    lifeStageCare: [
      { stage: 'Puppy (0-1 year)', description: 'Feed small-breed puppy food in measured portions. Begin socialization with gentle exposure to new experiences. Start basic training — Frenchies can be stubborn but respond well to positive reinforcement. Avoid overheating during play.' },
      { stage: 'Young Adult (1-2 years)', description: 'Transition to adult food. Establish moderate exercise routine — short walks, indoor play. Frenchies don\'t need extensive exercise. Monitor breathing during activity. Start dental care routine.' },
      { stage: 'Adult (2-8 years)', description: 'Maintain healthy weight — visible waistline from above. Clean skin folds 2-3 times weekly. Schedule annual vet visits including spine evaluations. Avoid exercise during hot weather. Use harness instead of collar to protect the trachea.' },
      { stage: 'Senior (8-10 years)', description: 'Watch for mobility changes that may indicate IVDD. Reduce stair usage. Switch to senior food. Schedule bi-annual vet visits. Monitor for breathing changes — elderly Frenchies may need airway management.' },
      { stage: 'Geriatric (10+ years)', description: 'Provide orthopedic bedding and ramps to furniture. Keep home cool with air conditioning. Monitor for pain and adjust care accordingly. Focus on quality of life and comfort. Watch closely for breathing distress.' },
    ],
    tips: [
      'Never exercise your Frenchie in hot weather — they can overheat in minutes',
      'Clean facial folds daily with gentle wipes to prevent skin infections',
      'Use a harness instead of a collar to protect their delicate trachea',
      'Maintain a healthy weight — obesity dramatically worsens breathing problems',
      'Consider pet insurance early — French Bulldogs often need specialized veterinary care',
      'Feed high-quality food to reduce allergy symptoms',
      'Avoid stairs and jumping from furniture to protect their spine',
    ],
    relatedSearches: [
      'french bulldog lifespan',
      'how long do french bulldogs live',
      'french bulldog health problems',
      'french bulldog ivdd',
      'french bulldog breathing problems',
      'french bulldog life expectancy',
    ],
  },

  'beagle-lifespan': {
    slug: 'beagle-lifespan',
    title: 'Beagle Lifespan: How Long Do Beagles Live?',
    metaTitle: 'Beagle Lifespan: How Long Do Beagles Live? | Complete Health Guide',
    metaDescription: 'Complete Beagle lifespan guide (12-15 years). Learn about common health issues, ear infections, obesity prevention, and proven tips to keep your Beagle healthy for years.',
    breedName: 'Beagle',
    size: 'Medium',
    weight: '20-30 lbs',
    lifespan: '12-15 years',
    avgLifespan: '13.5 years',
    humanAgeAt5: 39,
    humanAgeAt10: 64,
    lifeStages: 'Puppy: 0-1yr | Young Adult: 1-2yr | Adult: 2-8yr | Senior: 8-11yr | Geriatric: 11yr+',
    overview: 'Beagles are cheerful, curious, and famously food-motivated hounds with an incredible sense of smell. Their compact size, friendly disposition, and relatively long lifespan make them excellent family pets. Beagles are generally a healthy breed, but their love of food and unique physical characteristics create specific health challenges that owners should understand.',
    lifespanFactors: [
      'Obesity prevention through strict portion control',
      'Ear infection prevention and regular ear care',
      'Exercise and enrichment to prevent destructive behaviors',
      'Diet quality — Beagles benefit from high-quality, protein-rich food',
      'Genetic screening for epilepsy and hypothyroidism',
      'Dental care to prevent periodontal disease',
    ],
    commonHealthIssues: [
      { issue: 'Obesity', description: 'Beagles are among the most food-motivated breeds and can quickly become overweight. Obesity leads to joint problems, diabetes, heart disease, and reduced lifespan. Strict portion control and limited treats are essential.' },
      { issue: 'Ear Infections', description: 'Beagles\' long, floppy ears trap moisture and reduce airflow, creating an ideal environment for bacterial and yeast infections. Regular ear cleaning and thorough drying after baths or swimming is crucial.' },
      { issue: 'Epilepsy', description: 'Beagles have a higher than average rate of idiopathic epilepsy. Seizures typically begin between 6 months and 3 years of age. Most cases can be managed with medication.' },
      { issue: 'Hypothyroidism', description: 'An underactive thyroid gland causing weight gain, hair loss, and lethargy. Easily diagnosed with blood work and managed with daily medication.' },
      { issue: 'Intervertebral Disc Disease (IVDD)', description: 'Due to their long backs relative to short legs, Beagles can develop spinal disc problems. Avoid excessive jumping and maintain healthy weight to reduce risk.' },
      { issue: 'Cherry Eye', description: 'A prolapsed gland of the third eyelid that appears as a red mass in the corner of the eye. Requires surgical correction and is more common in younger Beagles.' },
    ],
    lifeStageCare: [
      { stage: 'Puppy (0-1 year)', description: 'Feed measured portions of puppy food — free-feeding leads to rapid weight gain. Begin crate training early. Start scent games and nose work to channel natural instincts. Socialize with people, dogs, and new environments.' },
      { stage: 'Young Adult (1-2 years)', description: 'Transition to adult food with strict portion control. Provide daily walks (30-45 minutes) and scent-based enrichment. Beagles were bred to follow their noses — always use a leash or secure fence. Continue obedience training.' },
      { stage: 'Adult (2-8 years)', description: 'Maintain lean body weight — you should feel ribs easily. Provide daily exercise and mental stimulation. Clean ears weekly. Schedule annual vet visits. Use puzzle feeders to slow eating and provide enrichment.' },
      { stage: 'Senior (8-11 years)', description: 'Monitor for weight gain as metabolism slows. Reduce high-impact exercise but maintain daily walks. Schedule bi-annual vet visits with thyroid screening. Watch for signs of arthritis and back problems.' },
      { stage: 'Geriatric (11+ years)', description: 'Provide soft, warm bedding for aging joints. Consider ramps for furniture access. Monitor for cognitive decline. Be patient with house training accidents. Focus on comfort and quality of life.' },
    ],
    tips: [
      'Measure every meal — never free-feed your Beagle',
      'Use puzzle feeders and snuffle mats to slow eating and provide mental stimulation',
      'Clean ears weekly with a vet-recommended ear cleaner',
      'Always leash your Beagle outdoors — their nose will override their recall training',
      'Provide daily scent-based activities like "find it" games or nose work',
      'Brush teeth 2-3 times weekly to prevent dental disease',
      'Keep treats to less than 10% of daily calories — use vegetables as low-calorie alternatives',
    ],
    relatedSearches: [
      'beagle lifespan',
      'how long do beagles live',
      'beagle health problems',
      'beagle life expectancy',
      'beagle ear infections',
      'beagle epilepsy',
    ],
  },

  'chihuahua-lifespan': {
    slug: 'chihuahua-lifespan',
    title: 'Chihuahua Lifespan: Why Chihuahuas Live So Long',
    metaTitle: 'Chihuahua Lifespan: How Long Do Chihuahuas Live? | Complete Guide',
    metaDescription: 'Discover why Chihuahuas live 14-16 years on average — one of the longest-living dog breeds. Learn about health issues, senior care, and how to maximize your Chihuahua\'s lifespan.',
    breedName: 'Chihuahua',
    size: 'Small',
    weight: '2-6 lbs',
    lifespan: '14-16 years',
    avgLifespan: '15 years',
    humanAgeAt5: 36,
    humanAgeAt10: 56,
    lifeStages: 'Puppy: 0-1yr | Young Adult: 1-2yr | Adult: 2-10yr | Senior: 10-14yr | Geriatric: 14yr+',
    overview: 'Chihuahuas are the smallest dog breed in the world and also one of the longest-living. Named after the Mexican state of Chihuahua, these tiny dogs pack enormous personality into a compact frame. Their exceptional longevity — with some Chihuahuas living into their early 20s — makes them unique in the canine world. Understanding the factors behind their long lifespan helps owners provide optimal care throughout this extended life journey.',
    lifespanFactors: [
      'Small body size is naturally correlated with longer canine lifespan',
      'Slower metabolic aging compared to larger breeds',
      'Genetic diversity in well-bred lines',
      'Dental care — critical for small dogs with crowded teeth',
      'Trauma prevention — their tiny size makes them vulnerable to injury',
      'Proper nutrition in tiny portions to prevent obesity',
    ],
    commonHealthIssues: [
      { issue: 'Dental Disease', description: 'Chihuahuas are extremely prone to dental problems due to their small mouths with crowded teeth. Periodontal disease can lead to heart, liver, and kidney problems. Regular professional dental cleanings are essential.' },
      { issue: 'Patellar Luxation', description: 'The kneecap slips out of its normal position, causing intermittent lameness. Affects up to 25% of Chihuahuas. Severe cases require surgical correction.' },
      { issue: 'Tracheal Collapse', description: 'The cartilage rings of the trachea weaken and flatten, causing a honking cough and breathing difficulty. Use a harness instead of a collar to reduce pressure on the trachea.' },
      { issue: 'Hypoglycemia', description: 'Low blood sugar is especially dangerous in tiny Chihuahua puppies. Can cause weakness, seizures, and unconsciousness. Feed small, frequent meals throughout the day.' },
      { issue: 'Heart Disease', description: 'Mitral valve disease is common in older Chihuahuas, causing heart murmurs and eventually congestive heart failure. Regular cardiac monitoring is important for seniors.' },
      { issue: 'Hydrocephalus', description: 'A buildup of fluid in the brain, more common in apple-headed Chihuahuas. Signs include a domed skull, seizures, and behavioral changes.' },
    ],
    lifeStageCare: [
      { stage: 'Puppy (0-1 year)', description: 'Feed small, frequent meals (3-4 daily) to prevent hypoglycemia. Begin gentle socialization — Chihuahuas need positive exposure to prevent fear-based behaviors. Start dental care early. Handle paws, ears, and mouth regularly for future grooming tolerance.' },
      { stage: 'Young Adult (1-2 years)', description: 'Transition to adult food in 2-3 small meals daily. Use a harness for walks. Establish exercise routine — short walks and indoor play suffice. Continue socialization. Begin regular dental care with brushing and vet cleanings.' },
      { stage: 'Adult (2-10 years)', description: 'Maintain oral health with daily brushing and annual dental cleanings. Keep weight in check — even 1 pound overweight is significant for a Chihuahua. Provide warm clothing in cold weather — they lose body heat quickly. Schedule annual senior blood work starting at age 5-6.' },
      { stage: 'Senior (10-14 years)', description: 'Switch to senior food. Schedule bi-annual vet visits including cardiac evaluations. Monitor for heart murmurs. Provide pet stairs for furniture access to prevent jumping injuries. Keep warm with sweaters and heated beds.' },
      { stage: 'Geriatric (14+ years)', description: 'Feed easily digestible senior food in multiple small meals. Monitor closely for signs of heart failure (coughing, exercise intolerance). Provide a calm, comfortable environment. Watch for cognitive decline. Cherish every moment with your long-lived companion.' },
    ],
    tips: [
      'Brush teeth daily — Chihuahuas have the highest rate of dental disease among all breeds',
      'Use a harness, never a collar, to protect the trachea',
      'Keep your Chihuahua warm — they are sensitive to cold due to their small body mass',
      'Supervise around larger dogs and small children to prevent accidental injury',
      'Schedule professional dental cleanings at least once per year',
      'Feed small, frequent meals to maintain stable blood sugar',
      'Consider pet stairs or ramps to prevent jumping-related joint injuries',
    ],
    relatedSearches: [
      'chihuahua lifespan',
      'how long do chihuahuas live',
      'chihuahua health problems',
      'why do chihuahuas live so long',
      'chihuahua life expectancy',
      'oldest chihuahua',
    ],
  },

  'poodle-lifespan': {
    slug: 'poodle-lifespan',
    title: 'Poodle Lifespan: Toy, Miniature, and Standard Poodle Life Expectancy',
    metaTitle: 'Poodle Lifespan: Toy, Mini & Standard Poodle Life Expectancy | Size Guide',
    metaDescription: 'Compare Poodle lifespans: Toy (14-16 years), Miniature (14-16 years), Standard (12-15 years). Learn about health issues by size, Addison\'s disease, bloat, and optimal care tips.',
    breedName: 'Poodle',
    size: 'Medium',
    weight: 'Toy: 4-6 lbs | Mini: 10-15 lbs | Standard: 45-70 lbs',
    lifespan: '12-16 years (varies by size)',
    avgLifespan: 'Toy & Mini: 14 years | Standard: 12.5 years',
    humanAgeAt5: '36 (toy/mini), 39 (standard)',
    humanAgeAt10: '56 (toy/mini), 64 (standard)',
    lifeStages: 'Varies significantly by size. Toy/Mini: longer adult stage. Standard: earlier senior transition.',
    overview: 'Poodles come in three size varieties — Toy, Miniature, and Standard — and each has distinct lifespan and health characteristics. Despite their elegant appearance, Poodles are athletic, intelligent, and versatile dogs originally bred as water retrievers. The lifespan differences between Poodle sizes offer a fascinating case study in how size affects canine aging even within a single breed.',
    lifespanFactors: [
      'Size variety — Toy and Miniature Poodles live longer than Standards',
      'Genetic diversity across bloodlines',
      'Regular professional grooming and skin health',
      'Eye health monitoring for progressive retinal atrophy',
      'Addison\'s disease screening, especially in Standards',
      'Exercise and mental stimulation to prevent anxiety',
    ],
    commonHealthIssues: [
      { issue: 'Addison\'s Disease', description: 'A hormonal disorder where the adrenal glands don\'t produce enough cortisol. More common in Standard Poodles. Symptoms include lethargy, vomiting, and collapse. Manageable with lifelong medication.' },
      { issue: 'Bloat (GDV)', description: 'A life-threatening emergency where the stomach twists. Primarily affects Standard Poodles due to their deep chest. Feed multiple small meals and avoid exercise after eating.' },
      { issue: 'Progressive Retinal Atrophy (PRA)', description: 'An inherited eye disease causing gradual vision loss. Affects all Poodle sizes. DNA testing is available to identify carriers and affected dogs.' },
      { issue: 'Hip Dysplasia', description: 'More common in Standard Poodles. This genetic joint condition causes arthritis and pain. Weight management and joint supplements help manage symptoms.' },
      { issue: 'Sebaceous Adenitis', description: 'An inflammatory skin disease affecting the sebaceous glands, causing hair loss and scaly skin. More common in Standard Poodles.' },
      { issue: 'Patellar Luxation', description: 'Kneecap dislocation, most common in Toy and Miniature Poodles. Can range from occasional to persistent lameness. Severe cases require surgery.' },
    ],
    lifeStageCare: [
      { stage: 'Puppy (0-1 year)', description: 'Feed size-appropriate puppy food. Standards: large-breed puppy food for controlled growth. Begin grooming desensitization early — Poodles need frequent professional grooming. Start basic obedience and socialization immediately.' },
      { stage: 'Young Adult (1-2 years)', description: 'Transition to adult food appropriate for size. Establish a grooming schedule every 4-6 weeks. Provide daily exercise and mental challenges — Poodles are among the smartest breeds and need brain stimulation.' },
      { stage: 'Adult (varies by size)', description: 'Standard Poodles: Adult until 7 years. Toy/Mini: Adult until 10 years. Maintain exercise routine and mental enrichment. Consider dog sports (agility, obedience, dock diving). Schedule annual vet visits.' },
      { stage: 'Senior (varies by size)', description: 'Standard Poodles: Senior at 7. Toy/Mini: Senior at 10. Switch to senior food. Schedule bi-annual vet visits. Watch for vision changes and cognitive decline. Reduce high-impact exercise.' },
      { stage: 'Geriatric (varies by size)', description: 'Provide comfortable bedding and easy home access. Monitor for Addisonian crisis signs in Standards. Keep grooming routine but shorter sessions. Focus on comfort, pain management, and quality of life.' },
    ],
    tips: [
      'Choose a Poodle size that fits your lifestyle — their care needs and lifespans differ significantly',
      'Budget for professional grooming every 4-6 weeks throughout your Poodle\'s life',
      'Provide daily mental stimulation — training, puzzle toys, and enrichment activities',
      'Brush teeth regularly — Toy Poodles are especially prone to dental disease',
      'Consider pet insurance for Standard Poodles, who may face higher medical costs',
      'Test for Addison\'s disease if your Standard Poodle shows unexplained vomiting or lethargy',
      'Learn to recognize bloat symptoms — a life-threatening emergency requiring immediate vet care',
    ],
    relatedSearches: [
      'poodle lifespan',
      'how long do poodles live',
      'toy poodle lifespan',
      'standard poodle life expectancy',
      'poodle health problems',
      'poodle addison disease',
    ],
  },

  'yorkshire-terrier-lifespan': {
    slug: 'yorkshire-terrier-lifespan',
    title: 'Yorkshire Terrier Lifespan: How Long Do Yorkies Live?',
    metaTitle: 'Yorkshire Terrier Lifespan: How Long Do Yorkies Live? | Complete Guide',
    metaDescription: 'Complete Yorkshire Terrier lifespan guide (13-15 years). Learn about Yorkie health issues, tracheal collapse, dental problems, and expert care tips for puppy through senior years.',
    breedName: 'Yorkshire Terrier',
    size: 'Small',
    weight: '4-7 lbs',
    lifespan: '13-15 years',
    avgLifespan: '14 years',
    humanAgeAt5: 36,
    humanAgeAt10: 56,
    lifeStages: 'Puppy: 0-1yr | Young Adult: 1-2yr | Adult: 2-10yr | Senior: 10-13yr | Geriatric: 13yr+',
    overview: 'Yorkshire Terriers, affectionately called "Yorkies," are one of the most popular toy breeds in the world. Despite their tiny size, Yorkies have big, bold personalities and a terrier\'s tenacious spirit. They are generally long-lived dogs with relatively few severe genetic disorders, but their small size creates specific health vulnerabilities that owners should be aware of.',
    lifespanFactors: [
      'Trauma prevention — their tiny size makes them fragile',
      'Dental care — small mouths lead to crowded teeth and periodontal disease',
      'Tracheal health — use harnesses, never collars',
      'Nutrition in tiny, appropriate portions',
      'Liver shunt screening in puppies',
      'Regular grooming and skin health monitoring',
    ],
    commonHealthIssues: [
      { issue: 'Dental Disease', description: 'Yorkies are highly prone to dental problems due to their tiny jaws with crowded teeth. Periodontal disease is nearly universal without preventive care. Daily brushing and professional cleanings are essential.' },
      { issue: 'Tracheal Collapse', description: 'A progressive weakening of the tracheal cartilage causing a honking cough. Affects many toy breeds. Always use a harness instead of a collar. Maintain healthy weight to reduce pressure.' },
      { issue: 'Portosystemic Shunt (Liver Shunt)', description: 'A congenital condition where blood bypasses the liver, failing to remove toxins. Symptoms include poor growth, seizures, and behavioral changes. Treatable with surgery or medical management.' },
      { issue: 'Patellar Luxation', description: 'Dislocating kneecap causing intermittent lameness. Common in toy breeds. Severe cases benefit from surgical correction.' },
      { issue: 'Legg-Calvé-Perthes Disease', description: 'A hip joint disorder where the femoral head degenerates due to insufficient blood supply. Typically appears between 4-12 months of age. Requires surgical treatment.' },
      { issue: 'Pancreatitis', description: 'Inflammation of the pancreas, often triggered by high-fat foods. Yorkies appear to have a genetic predisposition. Feed low-fat diet and avoid table scraps.' },
    ],
    lifeStageCare: [
      { stage: 'Puppy (0-1 year)', description: 'Feed small, frequent meals. Begin daily tooth brushing routine. Start socialization early — Yorkies need positive exposure to prevent fear behaviors. Handle paws, ears, and mouth for future grooming tolerance. House training requires patience — tiny bladders need frequent potty breaks.' },
      { stage: 'Young Adult (1-2 years)', description: 'Transition to adult food. Maintain daily dental care. Establish regular professional grooming schedule. Provide moderate exercise: daily walks and indoor play. Use a harness always. Continue training reinforcement.' },
      { stage: 'Adult (2-10 years)', description: 'Maintain strict dental care — daily brushing, regular professional cleanings. Keep at healthy weight — even half a pound matters. Use pet stairs for furniture. Schedule annual vet visits with blood work. Feed high-quality, low-fat food to prevent pancreatitis.' },
      { stage: 'Senior (10-13 years)', description: 'Switch to senior food. Increase vet visits to bi-annual. Monitor for signs of tracheal collapse (coughing, especially when excited). Watch for dental issues. Provide warm clothing in cold weather. Reduce exercise intensity but maintain daily walks.' },
      { stage: 'Geriatric (13+ years)', description: 'Feed easily digestible food. Monitor for cognitive decline and incontinence. Provide orthopedic bedding and easy access to everything. Be gentle during handling. Focus on comfort and quality of life.' },
    ],
    tips: [
      'Brush teeth daily — this is non-negotiable for Yorkies',
      'Always use a harness, never a collar, to protect the trachea',
      'Feed a low-fat diet to reduce pancreatitis risk',
      'Schedule professional dental cleanings annually',
      'Supervise around larger dogs and young children to prevent accidental injury',
      'Keep your Yorkie warm — their small size means they lose body heat quickly',
      'Be extremely careful about jumping from furniture — use pet stairs or ramps',
    ],
    relatedSearches: [
      'yorkshire terrier lifespan',
      'how long do yorkies live',
      'yorkie health problems',
      'yorkshire terrier life expectancy',
      'yorkie tracheal collapse',
      'teacup yorkie lifespan',
    ],
  },

  'boxer-lifespan': {
    slug: 'boxer-lifespan',
    title: 'Boxer Lifespan: How Long Do Boxers Live and How to Extend It',
    metaTitle: 'Boxer Lifespan: How Long Do Boxers Live? | Health & Care Guide',
    metaDescription: 'Complete Boxer lifespan guide (9-12 years). Learn about Boxer heart conditions, cancer risks, cardiomyopathy, and proven strategies to help your Boxer live a longer, healthier life.',
    breedName: 'Boxer',
    size: 'Large',
    weight: '55-70 lbs',
    lifespan: '9-12 years',
    avgLifespan: '10.5 years',
    humanAgeAt5: 39,
    humanAgeAt10: 64,
    lifeStages: 'Puppy: 0-1yr | Young Adult: 1-2yr | Adult: 2-6yr | Senior: 6-9yr | Geriatric: 9yr+',
    overview: 'Boxers are energetic, loyal, and playful dogs known for their boundless enthusiasm and affectionate nature. With their distinctive square head and muscular build, Boxers make excellent family guardians and companions. However, as a large breed with specific genetic predispositions, Boxers face significant health challenges — particularly cancer and heart disease — that owners should understand to maximize their dog\'s lifespan.',
    lifespanFactors: [
      'Cancer risk — Boxers have one of the highest cancer rates among all breeds',
      'Heart health monitoring for Boxer cardiomyopathy',
      'Responsible breeding with health certifications',
      'Temperature regulation — Boxers overheat easily due to their brachycephalic features',
      'Exercise management — they need activity but are prone to overheating',
      'Diet quality with anti-inflammatory nutrients',
    ],
    commonHealthIssues: [
      { issue: 'Cancer', description: 'The leading cause of death in Boxers. Lymphoma, mast cell tumors, and brain tumors are especially common. Studies show Boxers have higher cancer rates than most breeds. Regular lump checks and veterinary screening are essential.' },
      { issue: 'Boxer Cardiomyopathy', description: 'A genetic heart condition causing irregular heartbeats (arrhythmias) that can lead to sudden death. Affects approximately 20% of Boxers. Can sometimes be managed with medication. Annual Holter monitor testing is recommended.' },
      { issue: 'Aortic Stenosis', description: 'A congenital heart defect where the aortic valve is narrowed, forcing the heart to work harder. Can cause fainting, exercise intolerance, and heart failure. Screening by a veterinary cardiologist is important.' },
      { issue: 'Hip Dysplasia', description: 'Common in large breeds, causing joint pain and arthritis. OFA testing shows about 16% of Boxers have abnormal hips. Weight management and joint supplements help.' },
      { issue: 'Degenerative Myelopathy (DM)', description: 'A progressive spinal cord disease affecting older Boxers. Causes hind leg weakness and eventual paralysis. DNA testing is available.' },
      { issue: 'Bloat (GDV)', description: 'A life-threatening emergency where the stomach twists. Boxers\' deep chests put them at risk. Feed multiple small meals and avoid exercise after eating.' },
    ],
    lifeStageCare: [
      { stage: 'Puppy (0-1 year)', description: 'Feed large-breed puppy food for controlled growth. Begin socialization immediately — Boxers are naturally protective and need extensive positive exposure. Start basic obedience with positive reinforcement. Avoid overheating during play.' },
      { stage: 'Young Adult (1-2 years)', description: 'Transition to adult food. Establish a consistent exercise routine — Boxers have high energy but limit activity in hot weather. Schedule cardiac evaluation to establish baseline. Continue training and mental stimulation.' },
      { stage: 'Adult (2-6 years)', description: 'Schedule annual Holter monitor testing for arrhythmias. Monitor for lumps and bumps weekly. Provide 60+ minutes of exercise daily (in cool temperatures). Maintain ideal body weight. Feed 2-3 smaller meals to reduce bloat risk.' },
      { stage: 'Senior (6-9 years)', description: 'Increase vet visits to bi-annual including cardiac screening. Switch to senior food with joint support. Reduce exercise intensity. Monitor closely for cancer warning signs. Watch for mobility changes indicating DM.' },
      { stage: 'Geriatric (9+ years)', description: 'Comfortable orthopedic bedding is essential. Monitor heart health closely. Watch for signs of cognitive decline. Focus on pain management and quality of life. Provide gentle, consistent routine.' },
    ],
    tips: [
      'Schedule annual Holter monitor testing starting at age 2 to screen for Boxer cardiomyopathy',
      'Perform weekly full-body checks for lumps, bumps, and skin changes',
      'Never exercise your Boxer during hot weather — they overheat dangerously fast',
      'Feed 2-3 smaller meals daily instead of one large meal to reduce bloat risk',
      'Consider gastropexy surgery during spay/neuter to prevent bloat',
      'Choose a breeder who performs heart screenings (echocardiogram and Holter)',
      'Start joint supplements early as a preventive measure',
    ],
    relatedSearches: [
      'boxer lifespan',
      'how long do boxers live',
      'boxer health problems',
      'boxer cardiomyopathy',
      'boxer dog life expectancy',
      'boxer cancer rates',
    ],
  },

  'great-dane-lifespan': {
    slug: 'great-dane-lifespan',
    title: 'Great Dane Lifespan: Understanding the Gentle Giant\'s Years',
    metaTitle: 'Great Dane Lifespan: How Long Do Great Danes Live? | Giant Breed Guide',
    metaDescription: 'Complete Great Dane lifespan guide (8-10 years). Learn why giant breeds have shorter lives, bloat prevention, heart health, joint care, and how to maximize your Great Dane\'s precious years.',
    breedName: 'Great Dane',
    size: 'Giant',
    weight: '110-175 lbs',
    lifespan: '8-10 years',
    avgLifespan: '8.5 years',
    humanAgeAt5: '39-44',
    humanAgeAt10: '71-80',
    lifeStages: 'Puppy: 0-1yr | Young Adult: 1-2yr | Adult: 2-5yr | Senior: 5-7yr | Geriatric: 7yr+',
    overview: 'The Great Dane is the Apollo of dogs — majestic, gentle, and enormous. Known as "gentle giants," Great Danes form deep bonds with their families despite their imposing size. Tragically, giant breeds like Great Danes have significantly shorter lifespans than smaller dogs, averaging just 8-10 years. Understanding the unique challenges of giant breed aging helps owners provide the best possible care during their Dane\'s precious years.',
    lifespanFactors: [
      'Giant size — the largest dogs have the shortest natural lifespans',
      'Growth rate management during puppyhood',
      'Bloat prevention — the leading cause of death in Great Danes',
      'Heart health — dilated cardiomyopathy is common',
      'Joint protection during rapid growth phases',
      'Quality nutrition formulated for giant breed needs',
    ],
    commonHealthIssues: [
      { issue: 'Bloat (Gastric Dilatation-Volvulus)', description: 'The #1 killer of Great Danes. Their deep, narrow chests make them the breed at highest risk for stomach twisting. This is a life-threatening emergency. Prophylactic gastropexy (stomach tacking surgery) is strongly recommended.' },
      { issue: 'Dilated Cardiomyopathy (DCM)', description: 'A heart muscle disease causing the heart to enlarge and weaken. Affects up to 35% of Great Danes. Causes fatigue, coughing, and eventual heart failure. Annual cardiac screening is essential.' },
      { issue: 'Hip Dysplasia', description: 'Nearly universal in giant breeds. The rapid growth of Great Dane puppies puts enormous stress on developing joints. OFA testing, controlled growth, and joint supplements help manage this condition.' },
      { issue: 'Osteosarcoma (Bone Cancer)', description: 'Great Danes have an elevated risk of bone cancer compared to smaller breeds. Often appears as persistent lameness. Early detection is critical for treatment options.' },
      { issue: 'Wobbler Syndrome', description: 'A spinal condition affecting the neck vertebrae, causing a characteristic "wobbly" gait. Can cause pain, weakness, and paralysis. Treatment options include medication and surgery.' },
      { issue: 'Hypothyroidism', description: 'An underactive thyroid causing weight gain, hair loss, and lethargy. Easily managed with daily medication once diagnosed through blood work.' },
    ],
    lifeStageCare: [
      { stage: 'Puppy (0-1 year)', description: 'Critical period for controlled growth. Feed giant-breed puppy food with balanced calcium-phosphorus ratios. Avoid overfeeding — rapid growth damages joints. Avoid high-impact exercise on hard surfaces. Begin gentle socialization. Start basic obedience training.' },
      { stage: 'Young Adult (1-2 years)', description: 'Continue joint-conscious management until growth plates close (up to 18-24 months). Feed measured portions of adult giant-breed food. Establish moderate exercise routine — avoid excessive running. Schedule cardiac evaluation. Consider prophylactic gastropexy.' },
      { stage: 'Adult (2-5 years)', description: 'Maintain ideal body weight — lean is healthier for joints. Provide daily moderate exercise. Feed 2-3 smaller meals to reduce bloat risk (never exercise immediately after eating). Schedule annual vet visit with cardiac screening.' },
      { stage: 'Senior (5-7 years)', description: 'Switch to senior giant-breed food with joint support. Schedule bi-annual vet visits including heart evaluation. Watch for signs of DCM: coughing, exercise intolerance, weight loss. Provide orthopedic bedding. Reduce stair usage.' },
      { stage: 'Geriatric (7+ years)', description: 'Every day with a geriatric Great Dane is a gift. Provide comfortable, supportive bedding. Use ramps for vehicles. Monitor for pain and adjust medications accordingly. Focus on comfort, dignity, and quality of life. Cherish every moment.' },
    ],
    tips: [
      'Never exercise your Great Dane immediately before or after eating — wait at least 1 hour',
      'Discuss prophylactic gastropexy with your vet during spay/neuter surgery',
      'Feed 2-3 smaller meals daily instead of one large meal',
      'Use elevated food bowls — controversial but many Dane owners find them helpful',
      'Start joint supplements (glucosamine, chondroitin, MSM) during puppyhood',
      'Schedule annual cardiac evaluations starting at age 2',
      'Invest in a high-quality orthopedic bed — your Dane\'s joints will thank you',
    ],
    relatedSearches: [
      'great dane lifespan',
      'how long do great danes live',
      'great dane health problems',
      'great dane bloat',
      'why do great danes die young',
      'great dane dilated cardiomyopathy',
    ],
  },
};

export default breedArticles;

export const getBreedArticle = (slug: string): BreedArticle | undefined => {
  return breedArticles[slug];
};

export const getAllBreedSlugs = (): string[] => {
  return Object.keys(breedArticles);
};